var annotated_dup =
[
    [ "Buffer_Counter_TypeDef", "struct_buffer___counter___type_def.html", null ],
    [ "Buffer_Descriptor_TypeDef", "struct_buffer___descriptor___type_def.html", null ],
    [ "Buffer_StructTd", "struct_buffer___struct_td.html", null ],
    [ "BufferPingPong_structTd", "struct_buffer_ping_pong__struct_td.html", "struct_buffer_ping_pong__struct_td" ],
    [ "buttonMatrix_Coordinates_Td", "structbutton_matrix___coordinates___td.html", "structbutton_matrix___coordinates___td" ],
    [ "buttonMatrix_init_Td", "structbutton_matrix__init___td.html", "structbutton_matrix__init___td" ],
    [ "buttonMatrix_InterruptManagement_Td", "structbutton_matrix___interrupt_management___td.html", "structbutton_matrix___interrupt_management___td" ],
    [ "buttonMatrix_structTd", "structbutton_matrix__struct_td.html", "structbutton_matrix__struct_td" ],
    [ "ENC_TypeDef", "struct_e_n_c___type_def.html", null ],
    [ "EPD_BufferLocal_StructTd", "struct_e_p_d___buffer_local___struct_td.html", null ],
    [ "EPD_Check_StructTd", "struct_e_p_d___check___struct_td.html", null ],
    [ "EPD_GPIOs_StructTd", "struct_e_p_d___g_p_i_os___struct_td.html", null ],
    [ "EPD_StructTd", "struct_e_p_d___struct_td.html", null ],
    [ "Fonts_Descriptor_TypeDef", "struct_fonts___descriptor___type_def.html", null ],
    [ "Fonts_TypeDef", "struct_fonts___type_def.html", null ],
    [ "max7219_LED_TypeDef", "structmax7219___l_e_d___type_def.html", null ],
    [ "max7219_TypeDef", "structmax7219___type_def.html", "structmax7219___type_def" ],
    [ "MIDI_structTd", "struct_m_i_d_i__struct_td.html", "struct_m_i_d_i__struct_td" ],
    [ "MotorizedFader_internal_structTd", "struct_motorized_fader__internal__struct_td.html", "struct_motorized_fader__internal__struct_td" ],
    [ "MotorizedFader_structTd", "struct_motorized_fader__struct_td.html", null ],
    [ "PID_structTd", "struct_p_i_d__struct_td.html", "struct_p_i_d__struct_td" ],
    [ "SPIDMA_GPIOs_TypeDef", "struct_s_p_i_d_m_a___g_p_i_os___type_def.html", "struct_s_p_i_d_m_a___g_p_i_os___type_def" ],
    [ "SPIDMA_TypeDef", "struct_s_p_i_d_m_a___type_def.html", null ],
    [ "TB6612FNGMotorDriver_structTd", "struct_t_b6612_f_n_g_motor_driver__struct_td.html", "struct_t_b6612_f_n_g_motor_driver__struct_td" ],
    [ "Timer_structTd", "struct_timer__struct_td.html", "struct_timer__struct_td" ],
    [ "TSCButton_internal_structTd", "struct_t_s_c_button__internal__struct_td.html", "struct_t_s_c_button__internal__struct_td" ],
    [ "TSCButton_structTd", "struct_t_s_c_button__struct_td.html", null ],
    [ "Wiper_ADCdescriptor_structTd", "struct_wiper___a_d_cdescriptor__struct_td.html", "struct_wiper___a_d_cdescriptor__struct_td" ],
    [ "Wiper_Internal_StructTd", "struct_wiper___internal___struct_td.html", "struct_wiper___internal___struct_td" ],
    [ "Wiper_structTd", "struct_wiper__struct_td.html", "struct_wiper__struct_td" ],
    [ "WriteStringDescriptor_TypeDef", "struct_write_string_descriptor___type_def.html", null ]
];